function InitializeAllCustomFonts()
  surface.CreateFont("SSHL2RP_DermaMedium", {
    font = "Roboto",
    extended = false,
    size = 16,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
  });

  surface.CreateFont("SSHL2RP_DermaSubtitle", {
    font = "Roboto",
    extended = false,
    size = 24,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
  });

  surface.CreateFont("SSHL2RP_DermaAlmostLarge", {
    font = "Roboto",
    extended = false,
    size = 28,
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
  });
end
